<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lucas G. y Alex G.">

<title>Optativo R - Lucas G. y Alex G.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="R - Lucas G. y Alex G_files/libs/clipboard/clipboard.min.js"></script>
<script src="R - Lucas G. y Alex G_files/libs/quarto-html/quarto.js"></script>
<script src="R - Lucas G. y Alex G_files/libs/quarto-html/popper.min.js"></script>
<script src="R - Lucas G. y Alex G_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="R - Lucas G. y Alex G_files/libs/quarto-html/anchor.min.js"></script>
<link href="R - Lucas G. y Alex G_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="R - Lucas G. y Alex G_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="R - Lucas G. y Alex G_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="R - Lucas G. y Alex G_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="R - Lucas G. y Alex G_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Optativo R - Lucas G. y Alex G.</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lucas G. y Alex G. </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción"><strong>Introducción</strong></h2>
<p>En la sociedad, existen diversas nociones de muchas cosas, los sujetos se encuentran dentro sistemas con significados compartidos, es decir, en una realidad social intersubjetiva. Los estereotipos son unas de las tantas nociones que hay, en este caso específico se abordarán los estereotipos masculinos y la relación de aquello con los índices de dependencia económica de la mujer respecto al hombre.&nbsp;</p>
<p>Ahora bien, se entenderá por estereotipos masculinos todos aquellos <strong>rasgos (características) y capacidades</strong> que de un modo tradicional se consideran de el hombre teniendo como fundamento “<strong>la suposición de que algunas tareas o actitudes son propias de un sexo e impropias del otro</strong>, pero <strong>no se forman a partir de la reflexión sino que generalmente se consolidan</strong>” <span class="citation" data-cites="toca2008">(<a href="#ref-toca2008" role="doc-biblioref">Toca and Carreta 2008</a>)</span>. Los rasgos y capacidades atribuidos, serían características del hombre como: proveedor, fuerte, competitivo, valientes, dominantes, independientes, entre otros. Por otro lado, la <strong>dependencia económica</strong> se entenderá como aquella que es “visibilizada cuando los ingresos de la mujer <strong>son controlados por el cónyuge</strong>, y <strong>no se le permite de manera libre adquirir o comprar</strong>.” <span class="citation" data-cites="virgilio">(<a href="#ref-virgilio" role="doc-biblioref">Virgilio, n.d.</a>)</span>.</p>
<p>Si tenemos en cuenta que la dependencia económica da lugar y potencia una diversidad de violencias contra la mujer&nbsp; <span class="citation" data-cites="rodríguezenríquez2012">(<a href="#ref-rodríguezenríquez2012" role="doc-biblioref">Rodríguez Enríquez 2012</a>)</span> y que, la adherencia a estereotipos masculinos (y de género en su totalidad) “[…] <strong>oprimen y envilecen</strong> el correcto desarrollo de las aptitudes de la mujer. Intervienen gradualmente en la construcción femenina, una construcción que debe ser demolida…” <span class="citation" data-cites="bituga-nchama2021">(<a href="#ref-bituga-nchama2021" role="doc-biblioref">Bituga-Nchama 2021</a>)</span>. Es pertinente abordar como la dependencia económica se ve agravada por los estereotipos masculinos, ya que ambos fenómenos sociales suelen ser –en gran medida– difícil de percibir por la población general, siendo así factores antagonistas de la calidad de vida de la sociedad, pero principalmente la de las mujeres.</p>
<p>En este marco, dado lo que la literatura señala respecto a que la dependencia económica da lugar y potencia una diversidad de violencia contra la mujer, lo cual sumado al rol que juegan los estereotipos masculinos en la realidad social, nos lleva a plantearnos la siguiente hipótesis: a mayor grado de acuerdo con los estereotipos masculinos, mayor prevalencia de dependencia económica, y viceversa.</p>
<p>Para el desarrollo del análisis estadístico, se utilizó la base de datos de la Tercera Encuesta Nacional de Violencia Intrafamiliar contra la mujer y delitos sexuales (2017). La base de datos a manipular corresponde a una submuestra que contiene a las 1000 mujeres encuestadas en la Región Metropolitana, con un rango etario de 15 a 65 años. Se eligieron dos variables pertinentes a la problemática, por un lado el índice de acuerdo a los estereotipos masculinos <strong>(IND_MASC)</strong> y, por otro, el índice de dependencia económica <strong>(IND_DEPECON)</strong>. Por razones prácticas el índice de acuerdo a los estereotipos masculinos que va desde las puntuaciones del 0 al 60, donde 0 es nada de acuerdo y 60 muy de acuerdo, se ha recodificado en tres categorías: (1) 0-20; (2) 21-39; (3) 40-60. Aquello para poder visualizar mejor los datos en los gráficos y el respectivo cruce de variables en la tabla de contingencia.</p>
<p><strong>Segunda Parte: Asociación de variables y construcción de índices</strong></p>
<p>Para poder llevar a cabo la construcción de un índice con rigor, se realizó una revisión de bibliografía científica pertinente a la problemática planteada. Bajo este marco, en principio, se pensó en construir un <strong>índice de adhesión a estereotipos masculinos o de género</strong>, no obstante, tras una revisión extensa de bibliografía no se logró dar con una operacionalización de un índice con sus respectivas variables que sea lo suficientemente riguroso y exhaustivo. En este sentido, se optó por indagar con índices que se adecuen a la misma línea investigativa que se planteó en un comienzo, por consiguiente, se decanta por la construcción de un índice de Sexismo.</p>
<p>Este índice es multidimensional permitiendo medir el Sexismo, el cual se constituye por medio de dos dimensiones: (1) seximo hostil y (2) sexismo benevolente.</p>
<p><strong>Segunda Parte: Asociación de variables y construcción de índices</strong></p>
<p>Para poder llevar a cabo la construcción de un índice con rigor, se realizó una revisión de bibliografía científica pertinente a la problemática planteada. Bajo este marco, en principio, se pensó en construir un <strong>índice de adhesión a estereotipos masculinos o de género</strong>, no obstante, tras una revisión extensa de bibliografía no se logró dar con una operacionalización de un índice con sus respectivas variables que sea lo suficientemente riguroso y exhaustivo. En este sentido, se optó por indagar con índices que se adecuen a la misma línea investigativa que se planteó en un comienzo, por consiguiente, se decanta por la construcción de un índice de Sexismo.</p>
<p>Este índice es multidimensional permitiendo medir el Sexismo, el cual se constituye por medio de dos dimensiones: (1) seximo hostil y (2) sexismo benevolente.</p>
<p><img src="images/Captura%20de%20pantalla%202025-06-12%20235620-01.png" class="img-fluid"></p>
<p><img src="images/Captura%20de%20pantalla%202025-06-12%20235701-01.png" class="img-fluid"></p>
<p><strong>Figura 4:</strong> Operacionalización del Índice de Sexismo.&nbsp;</p>
<p><strong>Fuente:</strong> Maguiña, R., &amp; Roberth, F. (2018). <span class="citation" data-cites="maguiña">(<a href="#ref-maguiña" role="doc-biblioref">Maguiña, n.d.</a>)</span></p>
<p>En razón de la operacionalización planteada por Maguiña &amp; Roberth (2018)<span class="citation" data-cites="maguiña">(<a href="#ref-maguiña" role="doc-biblioref">Maguiña, n.d.</a>)</span>, para la construccion del <strong>Índice de Sexismo</strong> se utilizaron las siguientes variables del quinto eje temático <strong>[Opiniones y Actitudes respecto a roles masculinos y femeninos]</strong> de la base de datos de la Tercera Encuesta Nacional de Violencia Intrafamiliar contra la mujer y delitos sexuales (2017):</p>
<p><img src="images/Captura%20de%20pantalla%202025-06-13%20000240.png" class="img-fluid"></p>
<p><strong>Figura 5:</strong> Opiniones y Actitudes respecto a roles masculinos y femeninos</p>
<p><strong>Fuente:</strong> Cuestionario ENVIF (2017).</p>
<p><strong>Asociación entre variables.</strong></p>
<p>Antes de la construcción del ´Índice de Sexismo´, se llevó a cabo una asociación entre las 14 variables seleccionadas –explicitadas en la figura 5— que se consideraron pertinentes para constituir el índice en cuestión. De este modo, se buscó evaluar el grado de correlación entre las variables, con el objetivo de determinar si efectivamente se comportan de forma coherente entre sí, observando cómo y cuánto se relacionan las variaciones entre las variables.</p>
<p><strong>Matrices de correlación.</strong></p>
<ol type="1">
<li><strong>Matriz de correlación Pairwise.</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### 1. Primeros pasos ####</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Desactivamos notación científica</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co">#Desactivar la notación científica</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Establecer el directorio de trabajo</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/lucas/Documents/GitHub/Trabajo-1-OFC-R/Optativo R - Lucas G. y Alex G"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Instalar los paquetes a utilizar: la instalación de paquetes se realiza una sola vez.</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("pacman")</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#nstall.packages("psych")</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("BiocManager")</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman) <span class="co">#llamamos al paquete</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">packageVersion</span>(<span class="st">"texreg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] '1.39.4'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ahora podemos instalar paquetes mas fácilmente</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>               car,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>               tidyverse,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>               knitr,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>               haven, </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>               plotrix,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>               sjlabelled,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>               sjmisc,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>               stargazer,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>               texreg,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>               sjPlot,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>               kableExtra,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>               ggpubr,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>               labelled,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>               xlsx,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>               ggplot2,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>               summarytools,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>               knit,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>               psych,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>               GGally, <span class="co"># Correlaciones</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>               corrplot) <span class="co"># Correlaciones</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into 'C:/Users/lucas/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'knit' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.3:
  no fue posible abrir la URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.3/PACKAGES'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in p_install(package, character.only = TRUE, ...):</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
logical.return = TRUE, : there is no package called 'knit'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in pacman::p_load(dplyr, car, tidyverse, knitr, haven, plotrix, : Failed to install/load:
knit</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carga de base de datos</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Base_VIF <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="at">file =</span> <span class="st">"BBDD_VIF (2017).sav"</span>) <span class="co"># Encuesta Casen 2022</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#View(Base_VIF)</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">#names(Base_VIF)</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Selecion de variables pertinentes a la operacionalizacion</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>Base_VIF <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="at">file =</span> <span class="st">"BBDD_VIF (2017).sav"</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>indicadores2018 <span class="ot">&lt;-</span> Base_VIF <span class="sc">%&gt;%</span> <span class="fu">select</span>(P53_1_1, </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>                                       P53_1_2, </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>                                       P53_1_3, </span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>                                       P53_1_4, </span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>                                       P53_1_5, </span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>                                       P53_2_1, </span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>                                       P53_2_2, </span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>                                       P53_2_3, </span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>                                       P53_2_4, </span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>                                       P53_2_5, </span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>                                       P53_3_1, </span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>                                       P53_3_2, </span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>                                       P53_3_3, </span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>                                       P53_3_4)  <span class="sc">%&gt;%</span> </span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span> <span class="co"># Eliminar Na's</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_all</span>(<span class="sc">~</span>(<span class="fu">as.numeric</span>(.))) <span class="co"># Convertimos todas las variables a numéricas</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="do">##Eliminar No sabe [8]/No responde [9] </span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>indicadores2018[indicadores2018 <span class="sc">==</span> <span class="dv">8</span> <span class="sc">|</span> indicadores2018 <span class="sc">==</span> <span class="dv">9</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Eliminar los NA</span></span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>indicadores2018 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(indicadores2018)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a><span class="do">###Asociacion de Variables</span></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a><span class="do">###Matriz de Correlacion entre las variables que componen el Indice de Sexismo</span></span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_corr</span>(indicadores2018,</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>                 <span class="at">na.deletion =</span> <span class="st">"pairwise"</span>, <span class="co"># espeficicamos tratamiento NA</span></span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>                 <span class="at">triangle =</span> <span class="st">"lower"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_1_1</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_1_2</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_1_3</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_1_4</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_1_5</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_2_1</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_2_2</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_2_3</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_2_4</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_2_5</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_3_1</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_3_2</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_3_3</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">P53_3_4</td>
</tr>
<tr class="even">
<td style="font-style: italic">P53_1_1</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">P53_1_2</td>
<td style="text-align: center; padding: 0.2cm;">0.500<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">P53_1_3</td>
<td style="text-align: center; padding: 0.2cm;">0.462<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.572<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">P53_1_4</td>
<td style="text-align: center; padding: 0.2cm;">0.295<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.426<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.325<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">P53_1_5</td>
<td style="text-align: center; padding: 0.2cm;">0.397<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.516<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.480<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.532<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">P53_2_1</td>
<td style="text-align: center; padding: 0.2cm;">0.333<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.324<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.323<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.264<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.335<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">P53_2_2</td>
<td style="text-align: center; padding: 0.2cm;">0.392<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.502<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.457<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.384<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.451<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.391<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">P53_2_3</td>
<td style="text-align: center; padding: 0.2cm;">0.388<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.480<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.495<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.302<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.426<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.381<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.618<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">P53_2_4</td>
<td style="text-align: center; padding: 0.2cm;">0.375<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.500<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.448<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.452<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.563<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.374<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.548<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.503<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">P53_2_5</td>
<td style="text-align: center; padding: 0.2cm;">0.321<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.425<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.364<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.580<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.481<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.320<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.460<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.388<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.620<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">P53_3_1</td>
<td style="text-align: center; padding: 0.2cm;">0.369<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.407<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.362<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.310<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.399<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.335<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.402<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.399<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.446<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.387<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">P53_3_2</td>
<td style="text-align: center; padding: 0.2cm;">0.331<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.398<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.409<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.227<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.370<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.332<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.509<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.517<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.426<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.299<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.439<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">P53_3_3</td>
<td style="text-align: center; padding: 0.2cm;">0.294<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.391<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.327<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.557<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.444<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.294<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.413<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.344<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.474<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.603<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.425<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.319<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">P53_3_4</td>
<td style="text-align: center; padding: 0.2cm;">0.374<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.457<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.411<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.398<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.509<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.331<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.452<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.425<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.567<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.482<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.591<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.449<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.518<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td colspan="15" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with pairwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Figura 6: Elaboración Propia</p>
<p>Según la matriz de correlación Pairwise, se puede observar que entre las 14 variables seleccionadas, todas poseen una correlación estadísticamente significativa [*** = p&lt;0.001], en donde el grado de correlación más bajo –a comparación de los demás coeficientes— es de 0.264, mientras que el grado de correlación más alto es de 0.618. Considerando los criterios propuestos por Cohen (1988), es correcto afirmar que todas las correlaciones se orientan en una dirección positiva. En suma, dado que los coeficientes de correlación entre las 14 variables oscilan entre 0.264 y 0.618, es posible decir que la fuerza de las correlaciones se caracteriza por situarse, de forma generalizada, en el rango de ´Moderado´ [mayor a 0.3 y menor que 0.5], los cuales tienden al rango de ´Grande´ [mayor a 0.5]; es decir, la fuerza de las correlaciones tienden a ser más grandes que pequeñas.&nbsp;</p>
<p>En este sentido, se concluye que las 14 variables seleccionadas covarían consistentemente y, por consiguiente, resultan adecuadas para la construcción del Índice de Sexismo.</p>
<p><strong>Construcción del Índice de Sexismo.</strong></p>
<p>Teniendo en cuenta la operacionalización del <strong>Índice de Sexismo</strong> realizada por Maguiña, R., &amp; Roberth, F. (2018)<span class="citation" data-cites="maguiña">(<a href="#ref-maguiña" role="doc-biblioref">Maguiña, n.d.</a>)</span>, se seleccionaron las 14 variables según en qué dimensión era más adecuada catalogarlas.&nbsp;</p>
<p>En primer lugar, para la dimensión de ´Sexismo Hostil´ definida como: “Hace referencia al sexismo tradicional, basado en una supuesta inferioridad de las mujeres como grupo.” (Maguiña et at., 2018, p.&nbsp;22)<span class="citation" data-cites="maguiña">(<a href="#ref-maguiña" role="doc-biblioref">Maguiña, n.d.</a>)</span>. Las variables que más se corresponden a esta definición, son las siguientes:&nbsp;</p>
<p><strong>P53_1_2:</strong> Si una pareja no se pone de acuerdo sobre algo, la decisión final debería tomarla el hombre si es quién mantiene el hogar.</p>
<p><strong>P53_1_4:</strong> Las mujeres deberían aceptar de vez en cuando maltratos por la unidad de la familia y el bien de los hijos.&nbsp;&nbsp;</p>
<p><strong>P53_1_5:</strong> Por el bien de la relación una mujer no debiera tener amistades que no son del agrado de su pareja o marido.&nbsp;</p>
<p><strong>P53_2_1:</strong> Si hay golpes o maltrato en la casa, esto es un asunto que se resuelve en familia&nbsp;&nbsp;</p>
<p><strong>P53_2_4:</strong> Una mujer no debiera participar de una actividad social si no tiene el consentimiento de su esposo o pareja.&nbsp;&nbsp;</p>
<p><strong>P53_2_5:</strong> Para mantener una relación de pareja estable la mujer debiera acceder a tener relaciones sexuales, aunque ella no quiera.&nbsp;</p>
<p><strong>P53_3_1:</strong> Si a una mujer la acosan, probablemente tenga responsabilidad por usar ropa provocativa.&nbsp;</p>
<p><strong>P53_3_3:</strong> Es aceptable que la pareja/esposo de una mujer tenga el derecho de agredirla en caso de infidelidad.&nbsp;&nbsp;</p>
<p><strong>P53_3_4:</strong> El uso de vestimenta provocativa por parte de una mujer debe tener la aprobación previa de su pareja/marido.</p>
<p>En cuanto a la dimensión de ´Sexismo Benevolente´, definida como:&nbsp;</p>
<p>“Hace referencia a un tipo de sexismo más encubierto que se expresa a través de una intención de los hombres de cuidar a las mujeres, protegerlas y adorarlas y que se basa en una imagen de las mujeres también como seres inferiores pero con un tono afectivo más positivo.” (Maguiña, 2018, p.&nbsp;23)<span class="citation" data-cites="maguiña">(<a href="#ref-maguiña" role="doc-biblioref">Maguiña, n.d.</a>)</span></p>
<p>Las variables que más se corresponde a esta definición, son las siguientes:</p>
<p><strong>P53_1_1:</strong> En general una buena esposa debiera compartir la opinión de su esposo aunque ella no piense lo mismo.</p>
<p><strong>P53_1_3:</strong> Respetando la tradición cultural, es más adecuado que el hombre sea reconocido con el cargo de jefe del hogar.</p>
<p><strong>P53_2_2:</strong> Realizar los quehaceres del hogar es una tarea más adecuada para las mujeres que para los hombres.</p>
<p><strong>P53_2_3:</strong> Considero más adecuado que el hombre se responsabilice de los gastos de la familia y el hogar.&nbsp;</p>
<p><strong>P53_3_2:</strong> Considero más adecuado que las mujeres se hagan cargo del cuidado de los hijos, en vez del hombre.</p>
<p><strong>Porcentaje total del Índice de Sexismo y asignación del punto de corte.</strong></p>
<p>Una vez creado el Índice de Sexismo, mediante la revisión de literatura no se logró encontrar parámetros que nos indicarán límites o puntos de corte estándares para el Índice de Sexismo Ambivalente con el objetivo de obtener el porcentaje total de sexismo. Bajo este marco, se optó por utilizar el coeficiente del <strong>tercer cuartil [Q3= 2.322]</strong> del Índice de Sexismo como punto de corte; de este modo, se logró identificar al <strong>25% de mujeres con mayores niveles de sexismo</strong> en el total de la muestra<strong>.</strong> En este sentido, se utiliza un condicional que indica “Si” existe Sexismo cuando la variable “Sexismo” sea mayor o igual a 2.322 y, además, que indica “No” existe Sexismo cuando la variable “Sexismo” sea menor que 2.322.&nbsp;</p>
<p>Bajo estos parámetros, se observó que el <strong>74.91% de mujeres</strong> del total de la muestra <strong>no se clasifica como sexista</strong>, mientras que el <strong>25.08% de mujeres si se clasifica como sexista.</strong></p>
<p><strong>Estimación de consistencia interna.</strong></p>
<ol type="A">
<li>Alfa de Cronbach para los ítems de la dimensión: Sexismo Hostil.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">###Creacion de Dimensiones con sus respectivos indicadores</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>indicadores2018 <span class="ot">=</span> indicadores2018 <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sexismo_Hostil =</span> <span class="fu">mean</span>(<span class="fu">c</span>(P53_1_2, P53_1_4, P53_1_5, P53_2_1, P53_2_4, P53_2_5, P53_3_1, P53_3_3, P53_3_4)),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">Sexismo_Benevolente =</span> <span class="fu">mean</span>(<span class="fu">c</span>(P53_1_1, P53_1_3, P53_2_2, P53_2_3, P53_3_2))) <span class="sc">%&gt;%</span> </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Creacion del Indice de Sexismo</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>indicadores2018 <span class="ot">=</span> indicadores2018 <span class="sc">%&gt;%</span> </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Indice_Sexismo =</span> <span class="fu">mean</span>(<span class="fu">c</span>(Sexismo_Hostil, Sexismo_Benevolente))) <span class="sc">%&gt;%</span> </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>indicadores2018 <span class="sc">%&gt;%</span> <span class="fu">select</span>(Indice_Sexismo) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>) <span class="co"># Primeros 10 casos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 1
   Indice_Sexismo
            &lt;dbl&gt;
 1           1.62
 2           2.12
 3           2.52
 4           2.09
 5           1.62
 6           2.18
 7           2.42
 8           2.67
 9           1   
10           2.37</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(indicadores2018<span class="sc">$</span>Indice_Sexismo) <span class="co"># Resumen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   1.356   2.000   1.933   2.322   5.000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Porcentaje Total de Indice_Sexismo</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>indicadores2018_Porcentaje <span class="ot">&lt;-</span> indicadores2018 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Indice_Sexismo =</span> <span class="fu">case_when</span>(Indice_Sexismo<span class="sc">&gt;=</span><span class="fl">2.322</span><span class="sc">~</span><span class="st">"si"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                                                                                    Indice_Sexismo<span class="sc">&lt;</span><span class="fl">2.322</span><span class="sc">~</span><span class="st">"no"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(indicadores2018_Porcentaje<span class="sc">$</span>Indice_Sexismo))<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      no       si 
74.91932 25.08068 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecciona solo los ítems de la dimensión "Sexismo Hostil"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>items_hostil <span class="ot">&lt;-</span> indicadores2018 <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(P53_1_2, P53_1_4, P53_1_5, P53_2_1, P53_2_4, P53_2_5, P53_3_1, P53_3_3, P53_3_4)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcula el Alfa de Cronbach para esa dimensión</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(items_hostil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = items_hostil)

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
      0.86      0.88    0.88      0.45 7.2 0.0026  1.7 0.59     0.44

    95% confidence boundaries 
         lower alpha upper
Feldt     0.85  0.86  0.86
Duhachek  0.85  0.86  0.86

 Reliability if an item is dropped:
        raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
P53_1_2      0.84      0.87    0.87      0.45 6.5   0.0029 0.0110  0.45
P53_1_4      0.85      0.87    0.86      0.45 6.5   0.0028 0.0086  0.44
P53_1_5      0.84      0.86    0.86      0.44 6.2   0.0030 0.0103  0.43
P53_2_1      0.87      0.88    0.88      0.48 7.4   0.0024 0.0060  0.48
P53_2_4      0.83      0.86    0.85      0.43 6.0   0.0030 0.0093  0.42
P53_2_5      0.84      0.86    0.85      0.43 6.1   0.0029 0.0083  0.43
P53_3_1      0.85      0.87    0.87      0.45 6.7   0.0028 0.0097  0.47
P53_3_3      0.84      0.86    0.86      0.44 6.3   0.0029 0.0094  0.44
P53_3_4      0.83      0.86    0.86      0.44 6.2   0.0031 0.0096  0.43

 Item statistics 
           n raw.r std.r r.cor r.drop mean   sd
P53_1_2 6507  0.70  0.69  0.64   0.60  1.9 0.90
P53_1_4 6507  0.66  0.71  0.66   0.59  1.5 0.59
P53_1_5 6507  0.74  0.75  0.71   0.65  1.7 0.84
P53_2_1 6507  0.61  0.56  0.46   0.44  2.2 1.19
P53_2_4 6507  0.77  0.78  0.76   0.70  1.7 0.77
P53_2_5 6507  0.72  0.76  0.74   0.66  1.5 0.60
P53_3_1 6507  0.71  0.67  0.62   0.58  2.0 1.09
P53_3_3 6507  0.70  0.73  0.70   0.63  1.5 0.62
P53_3_4 6507  0.77  0.76  0.73   0.68  1.8 0.91

Non missing response frequency for each item
           1    2    3    4    5 miss
P53_1_2 0.37 0.50 0.03 0.08 0.01    0
P53_1_4 0.57 0.41 0.01 0.01 0.00    0
P53_1_5 0.47 0.44 0.03 0.06 0.01    0
P53_2_1 0.34 0.40 0.03 0.20 0.03    0
P53_2_4 0.44 0.50 0.02 0.04 0.01    0
P53_2_5 0.53 0.45 0.01 0.01 0.00    0
P53_3_1 0.39 0.42 0.03 0.14 0.02    0
P53_3_3 0.52 0.45 0.01 0.01 0.00    0
P53_3_4 0.45 0.44 0.03 0.07 0.01    0</code></pre>
</div>
</div>
<p>Observando el ´raw_alpha´ equivalente a 0.86 y el ´std.alpha´ equivalente 0.88, podemos señalar que hay una alta consistencia interna acercándose al valor máximo esperado de 0.9 puntos (Oviedo, 2005)<span class="citation" data-cites="oviedo2005">(<a href="#ref-oviedo2005" role="doc-biblioref">Oviedo and Campo-Arias 2005</a>)</span>. Por consiguiente, todos los ítems contribuyen de forma consistente a la dimensión ´Sexismo Hostil´. &nbsp;&nbsp;&nbsp;&nbsp;</p>
<ol start="2" type="A">
<li><strong>Alfa de Cronbach para los ítems de la dimensión: Sexismo Benevolente.</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecciona solo los ítems de la dimensión "Sexismo Benevolente"</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>items_benevolente <span class="ot">&lt;-</span> indicadores2018 <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(P53_1_1, P53_1_3, P53_2_2, P53_2_3, P53_3_2)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(items_benevolente)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = items_benevolente)

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
       0.8      0.81    0.78      0.46 4.2 0.0039  2.1 0.84     0.46

    95% confidence boundaries 
         lower alpha upper
Feldt     0.79   0.8  0.81
Duhachek  0.79   0.8  0.81

 Reliability if an item is dropped:
        raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
P53_1_1      0.80      0.80    0.76      0.50 4.0   0.0041 0.0049  0.50
P53_1_3      0.76      0.77    0.73      0.46 3.4   0.0049 0.0114  0.45
P53_2_2      0.75      0.75    0.71      0.43 3.1   0.0051 0.0050  0.44
P53_2_3      0.74      0.75    0.70      0.43 3.0   0.0053 0.0039  0.43
P53_3_2      0.77      0.78    0.74      0.47 3.5   0.0047 0.0071  0.46

 Item statistics 
           n raw.r std.r r.cor r.drop mean   sd
P53_1_1 6507  0.71  0.68  0.55   0.50  2.4 1.28
P53_1_3 6507  0.75  0.75  0.66   0.59  2.1 1.07
P53_2_2 6507  0.77  0.79  0.73   0.65  1.9 0.95
P53_2_3 6507  0.79  0.80  0.75   0.66  2.1 1.11
P53_3_2 6507  0.74  0.74  0.63   0.56  2.2 1.18

Non missing response frequency for each item
           1    2    3    4    5 miss
P53_1_1 0.30 0.36 0.03 0.26 0.05    0
P53_1_3 0.34 0.45 0.05 0.14 0.02    0
P53_2_2 0.37 0.48 0.03 0.09 0.02    0
P53_2_3 0.33 0.44 0.04 0.16 0.03    0
P53_3_2 0.33 0.41 0.04 0.18 0.04    0</code></pre>
</div>
</div>
<p>Para el ´Sexismo Benevolente´ tenemos que el ´raw_alpha´ equivalente a 0.8 y el ´std.alpha´ 0.81 también indican un alta consistencia interna. Por consiguiente, todos los ítems contribuyen de forma consistente a la dimensión de ´Sexismo Benevolente´.</p>
<ol start="3" type="A">
<li><strong>Alfa de Cronbach para los ítems del Índice de Sexismo: (1) Sexismo Hostil; (2) Sexismo Benevolente.</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecciona solo los ítems del Indice de Sexismo</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>items_Indice_Sexismo <span class="ot">&lt;-</span> indicadores2018 <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(P53_1_2, P53_1_4, P53_1_5, P53_2_1, P53_2_4, P53_2_5, P53_3_1, P53_3_3, P53_3_4, P53_1_1, P53_1_3, P53_2_2, P53_2_3, P53_3_2)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(items_Indice_Sexismo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = items_Indice_Sexismo)

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
       0.9      0.91    0.92      0.42  10 0.0018  1.9 0.64     0.41

    95% confidence boundaries 
         lower alpha upper
Feldt      0.9   0.9   0.9
Duhachek   0.9   0.9   0.9

 Reliability if an item is dropped:
        raw_alpha std.alpha G6(smc) average_r  S/N alpha se  var.r med.r
P53_1_2      0.89      0.90    0.91      0.42  9.3   0.0019 0.0080  0.40
P53_1_4      0.90      0.91    0.91      0.43  9.7   0.0018 0.0066  0.42
P53_1_5      0.89      0.90    0.91      0.42  9.3   0.0019 0.0080  0.40
P53_2_1      0.90      0.91    0.92      0.44 10.1   0.0018 0.0072  0.43
P53_2_4      0.89      0.90    0.91      0.41  9.1   0.0019 0.0072  0.40
P53_2_5      0.89      0.90    0.91      0.42  9.4   0.0019 0.0070  0.41
P53_3_1      0.89      0.91    0.91      0.42  9.6   0.0019 0.0081  0.43
P53_3_3      0.90      0.91    0.91      0.42  9.5   0.0019 0.0073  0.41
P53_3_4      0.89      0.90    0.91      0.42  9.3   0.0019 0.0077  0.40
P53_1_1      0.90      0.91    0.91      0.43  9.8   0.0018 0.0078  0.43
P53_1_3      0.89      0.90    0.91      0.42  9.5   0.0019 0.0080  0.41
P53_2_2      0.89      0.90    0.91      0.42  9.2   0.0020 0.0078  0.40
P53_2_3      0.89      0.90    0.91      0.42  9.4   0.0019 0.0077  0.41
P53_3_2      0.89      0.91    0.91      0.43  9.7   0.0019 0.0075  0.42

 Item statistics 
           n raw.r std.r r.cor r.drop mean   sd
P53_1_2 6507  0.73  0.72  0.70   0.67  1.9 0.90
P53_1_4 6507  0.58  0.64  0.61   0.54  1.5 0.59
P53_1_5 6507  0.71  0.72  0.70   0.65  1.7 0.84
P53_2_1 6507  0.59  0.56  0.50   0.49  2.2 1.19
P53_2_4 6507  0.74  0.77  0.75   0.70  1.7 0.77
P53_2_5 6507  0.66  0.71  0.69   0.62  1.5 0.60
P53_3_1 6507  0.67  0.66  0.62   0.59  2.0 1.09
P53_3_3 6507  0.63  0.67  0.65   0.58  1.5 0.62
P53_3_4 6507  0.72  0.73  0.71   0.67  1.8 0.91
P53_1_1 6507  0.65  0.61  0.57   0.55  2.4 1.28
P53_1_3 6507  0.69  0.68  0.64   0.62  2.1 1.07
P53_2_2 6507  0.74  0.73  0.71   0.68  1.9 0.95
P53_2_3 6507  0.72  0.70  0.68   0.65  2.1 1.11
P53_3_2 6507  0.66  0.63  0.59   0.58  2.2 1.18

Non missing response frequency for each item
           1    2    3    4    5 miss
P53_1_2 0.37 0.50 0.03 0.08 0.01    0
P53_1_4 0.57 0.41 0.01 0.01 0.00    0
P53_1_5 0.47 0.44 0.03 0.06 0.01    0
P53_2_1 0.34 0.40 0.03 0.20 0.03    0
P53_2_4 0.44 0.50 0.02 0.04 0.01    0
P53_2_5 0.53 0.45 0.01 0.01 0.00    0
P53_3_1 0.39 0.42 0.03 0.14 0.02    0
P53_3_3 0.52 0.45 0.01 0.01 0.00    0
P53_3_4 0.45 0.44 0.03 0.07 0.01    0
P53_1_1 0.30 0.36 0.03 0.26 0.05    0
P53_1_3 0.34 0.45 0.05 0.14 0.02    0
P53_2_2 0.37 0.48 0.03 0.09 0.02    0
P53_2_3 0.33 0.44 0.04 0.16 0.03    0
P53_3_2 0.33 0.41 0.04 0.18 0.04    0</code></pre>
</div>
</div>
<p>Evaluando el Índice de Sexismo con los 14 ítems, se obtuvo un ´raw_alpha´ equivalente a 0.9 y un ´std.alpha´ de 0.91, lo cual permite señalar que hay <strong>una alta consistencia interna</strong>. Si bien el ´sdt.alpha´ de 0.91 supera los 0.90 puntos, no implica necesariamente redundancia entre los ítems. Como se vio anteriormente, los ítems utilizados abordan diferentes manifestaciones de sexismo (ya sea hostil o benevolente), por consiguiente, se considera adecuado afirmar que los 14 ítems contribuyen de forma consistente al constructo del Índice de Sexismo.</p>
<p><strong>Tercera parte: Regresiones lineales.</strong></p>
<p>Posterior a la creación del Índice de Sexismo, se realizaron, en primera instancia, regresiones lineales simples. Por un lado, se realiza un cruce de las variables independientes ´Tiempo con la pareja Actual´ y ´Edad´–de la mujer– con la variable dependiente “Índice de Sexismo” para observar cómo se asocian de forma gráfica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecciona solo los ítems del Indice de Sexismo</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>items_Indice_Sexismo <span class="ot">&lt;-</span> indicadores2018 <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(P53_1_2, P53_1_4, P53_1_5, P53_2_1, P53_2_4, P53_2_5, P53_3_1, P53_3_3, P53_3_4, P53_1_1, P53_1_3, P53_2_2, P53_2_3, P53_3_2)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(items_Indice_Sexismo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = items_Indice_Sexismo)

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
       0.9      0.91    0.92      0.42  10 0.0018  1.9 0.64     0.41

    95% confidence boundaries 
         lower alpha upper
Feldt      0.9   0.9   0.9
Duhachek   0.9   0.9   0.9

 Reliability if an item is dropped:
        raw_alpha std.alpha G6(smc) average_r  S/N alpha se  var.r med.r
P53_1_2      0.89      0.90    0.91      0.42  9.3   0.0019 0.0080  0.40
P53_1_4      0.90      0.91    0.91      0.43  9.7   0.0018 0.0066  0.42
P53_1_5      0.89      0.90    0.91      0.42  9.3   0.0019 0.0080  0.40
P53_2_1      0.90      0.91    0.92      0.44 10.1   0.0018 0.0072  0.43
P53_2_4      0.89      0.90    0.91      0.41  9.1   0.0019 0.0072  0.40
P53_2_5      0.89      0.90    0.91      0.42  9.4   0.0019 0.0070  0.41
P53_3_1      0.89      0.91    0.91      0.42  9.6   0.0019 0.0081  0.43
P53_3_3      0.90      0.91    0.91      0.42  9.5   0.0019 0.0073  0.41
P53_3_4      0.89      0.90    0.91      0.42  9.3   0.0019 0.0077  0.40
P53_1_1      0.90      0.91    0.91      0.43  9.8   0.0018 0.0078  0.43
P53_1_3      0.89      0.90    0.91      0.42  9.5   0.0019 0.0080  0.41
P53_2_2      0.89      0.90    0.91      0.42  9.2   0.0020 0.0078  0.40
P53_2_3      0.89      0.90    0.91      0.42  9.4   0.0019 0.0077  0.41
P53_3_2      0.89      0.91    0.91      0.43  9.7   0.0019 0.0075  0.42

 Item statistics 
           n raw.r std.r r.cor r.drop mean   sd
P53_1_2 6507  0.73  0.72  0.70   0.67  1.9 0.90
P53_1_4 6507  0.58  0.64  0.61   0.54  1.5 0.59
P53_1_5 6507  0.71  0.72  0.70   0.65  1.7 0.84
P53_2_1 6507  0.59  0.56  0.50   0.49  2.2 1.19
P53_2_4 6507  0.74  0.77  0.75   0.70  1.7 0.77
P53_2_5 6507  0.66  0.71  0.69   0.62  1.5 0.60
P53_3_1 6507  0.67  0.66  0.62   0.59  2.0 1.09
P53_3_3 6507  0.63  0.67  0.65   0.58  1.5 0.62
P53_3_4 6507  0.72  0.73  0.71   0.67  1.8 0.91
P53_1_1 6507  0.65  0.61  0.57   0.55  2.4 1.28
P53_1_3 6507  0.69  0.68  0.64   0.62  2.1 1.07
P53_2_2 6507  0.74  0.73  0.71   0.68  1.9 0.95
P53_2_3 6507  0.72  0.70  0.68   0.65  2.1 1.11
P53_3_2 6507  0.66  0.63  0.59   0.58  2.2 1.18

Non missing response frequency for each item
           1    2    3    4    5 miss
P53_1_2 0.37 0.50 0.03 0.08 0.01    0
P53_1_4 0.57 0.41 0.01 0.01 0.00    0
P53_1_5 0.47 0.44 0.03 0.06 0.01    0
P53_2_1 0.34 0.40 0.03 0.20 0.03    0
P53_2_4 0.44 0.50 0.02 0.04 0.01    0
P53_2_5 0.53 0.45 0.01 0.01 0.00    0
P53_3_1 0.39 0.42 0.03 0.14 0.02    0
P53_3_3 0.52 0.45 0.01 0.01 0.00    0
P53_3_4 0.45 0.44 0.03 0.07 0.01    0
P53_1_1 0.30 0.36 0.03 0.26 0.05    0
P53_1_3 0.34 0.45 0.05 0.14 0.02    0
P53_2_2 0.37 0.48 0.03 0.09 0.02    0
P53_2_3 0.33 0.44 0.04 0.16 0.03    0
P53_3_2 0.33 0.41 0.04 0.18 0.04    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">################################################################################################</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="do">###Regresiones Lineales</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="do">##Selecionamos las variables que utilizaremos, tanto la variable dependiente como predictores.</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>variables_reg_lin <span class="ot">&lt;-</span> Base_VIF <span class="sc">%&gt;%</span> <span class="fu">select</span>(EDAD_O, P4,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                                         GSE_REC,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                                         P26_REC,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                                         P12_H,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>                                         IND_DEPECON,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>                                         RVGENV_AoV,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                                         VPGENV_AoV,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>                                         IND_REDES,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>                                         VE_AÑO,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>                                         PJFINALroles)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co">#Eliminar No sabe [8]/No responde [9] </span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>variables_reg_lin[variables_reg_lin <span class="sc">==</span> <span class="dv">8</span> <span class="sc">|</span> variables_reg_lin <span class="sc">==</span> <span class="dv">9</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>variables_reg_lin[variables_reg_lin <span class="sc">==</span> <span class="dv">88</span> <span class="sc">|</span> variables_reg_lin <span class="sc">==</span> <span class="dv">99</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Eliminar los NA</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>variables_reg_lin <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(variables_reg_lin)</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="do">##Pasar la variable dependiente "PJFINALroles" [Indice de Sexismo= 14 items de la variable P53] a númerica</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>variables_reg_lin<span class="sc">$</span>PJFINALroles <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(variables_reg_lin<span class="sc">$</span>PJFINALroles))</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="co">#Vemos como se comportan graficamente la asociacion entre variables relevantes </span></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a><span class="co">#[Tiempo con la Pareja Actual y Edad de la Mujer con la variable Dependiente: Indice de Sexismo]</span></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico x1 = A CT</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>graph1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(variables_reg_lin, <span class="fu">aes</span>(<span class="at">x =</span> P26_REC, <span class="at">y =</span> PJFINALroles)) <span class="sc">+</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Puntos</span></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>  <span class="co"># Recta de regresión</span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tiempo con la Pareja actual"</span>, <span class="at">y =</span> <span class="st">"Indice de Sexismo"</span>)  <span class="co"># Etiquetas de ejes</span></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico 2</span></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>graph2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(variables_reg_lin, <span class="fu">aes</span>(<span class="at">x =</span> EDAD_O, <span class="at">y =</span> PJFINALroles)) <span class="sc">+</span></span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Edad"</span>, <span class="at">y =</span> <span class="st">"Indice de Sexismo"</span>)</span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span> (graph1, graph2, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="co"># Unir graficos </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R---Lucas-G.-y-Alex-G_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;<strong>Figura 7:</strong> Gráfico de asociación de predictores relevantes con la variable dependiente.</p>
<p>En la <strong>figura 7</strong> se puede observar que tanto el predictor ´Tiempo con la pareja actual´ como el predictor ´Edad´ poseen una asociación positiva con el Índice de Sexismo. Sin embargo, el tamaño de efecto de ´Edad´ se caracteriza por ser grande, mientras que el efecto de ´Tiempo con la pareja actual´ es pequeño.</p>
<p><strong>Regresión Lineal sin predictores.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Valor de la regresion lineal sin predictores</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>variables_reg_lin<span class="sc">$</span>P4 <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(variables_reg_lin<span class="sc">$</span>P4)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>variables_reg_lin<span class="sc">$</span>IND_DEPECON <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(variables_reg_lin<span class="sc">$</span>IND_DEPECON)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>variables_reg_lin <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(variables_reg_lin)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(PJFINALroles <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>variables_reg_lin)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg1, <span class="at">type=</span><span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                           PJFINALroles        
-----------------------------------------------
Constant                     2.058***          
                              (0.013)          
                                               
-----------------------------------------------
Observations                   3,235           
R2                             0.000           
Adjusted R2                    0.000           
Residual Std. Error      0.737 (df = 3234)     
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Teniendo solo la regresión lineal sin predictores, es decir, solo con la variable dependiente, se observa en el intercepto un valor de 2.058 en promedio del Índice de Sexismo en las mujeres.</p>
<p><strong>Regresiones Lineales.</strong></p>
<ol type="A">
<li><strong>Regresiones lineales simples.</strong></li>
</ol>
<p>Posteriormente se realizan 10 modelos de regresiones lineales simples con predictores considerados como pertinentes para explicar la variable dependiente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Regresion Lineal Simple [Parte 1: Modelos del 1 al 5] </span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co">#reg2 &lt;- lm(PJFINALroles ~ EDAD_O, data=variables_reg_lin)</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co">#reg3 &lt;- lm(PJFINALroles ~ P4, data=variables_reg_lin)</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co">#reg4 &lt;- lm(PJFINALroles ~ IND_DEPECON, data=variables_reg_lin)</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co">#reg5 &lt;- lm(PJFINALroles ~ RVGENV_AoV, data=variables_reg_lin)</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co">#reg6 &lt;- lm(PJFINALroles ~ VPGENV_AoV, data=variables_reg_lin)</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#knitreg(list(reg2, reg3, reg4, reg5, reg6), </span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>        <span class="co">#custom.model.names = c("Modelo 1",</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>                               <span class="co">#"Modelo 2",</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>                               <span class="co">#"Modelo 3",</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>                               <span class="co">#"Modelo 4",</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>                               <span class="co">#"Modelo 5"),</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>        <span class="co">#custom.note = "*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05",</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>        <span class="co">#custom.coef.names = c("Intercepto", </span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>                              <span class="co">#"Edad",</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>                              <span class="co">#"Sin estudios &lt;br&gt; &lt;i&gt;(Ref. Ed. básica)&lt;/i&gt;",</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>                              <span class="co">#"Educación media",</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>                              <span class="co">#"Educación superior",</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>                        <span class="co">#"Si dependencia economica &lt;br&gt; &lt;i&gt;(Ref. No dependencia economica)&lt;/i&gt;",</span></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>                              <span class="co">#"Violencia Fisica a lo largo de la Vida",</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>                              <span class="co">#"Violencia Psicologica a lo largo de la vida"),</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>        <span class="co">#caption = "Indice de Sexismo",</span></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>        <span class="co">#caption.above = TRUE) </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/Captura%20de%20pantalla%202025-06-13%20231245.png" class="img-fluid"></p>
<p>En el modelo 1 se utilizó ´Edad´ como predictor, este posee un coeficiente de regresión de 0.01, siendo de forma alta estadísticamente significativo. Esto sugiere que por cada unidad que aumenta la edad, el Índice de Sexismo aumenta en promedio 0.01 unidades, en donde dicho efecto puede extrapolarse a la población con un 99.9% de confianza [***: p&lt;0.001]. Por otro lado, el intercepto equivalente a 1.54 indica que –teóricamente— una persona con edad 0 tendría un promedio en el Índice de Sexismo de 1.54. Finalmente, dado el R2 equivalente a 0.04, se entiende que el modelo logra explicar en un 4% la varianza de la variable dependiente.</p>
<p>En el modelo 2 se utilizó ´Nivel educativo´ como predictor, el cual se subdivide en 4 categorías: Sin estudios, Educación Básica, Educación Media y Educación Superior. En donde se toma como base –referencia— la categoría ´Educación Básica´. Se observa que las mujeres con ´Educación Media´ poseen en promedio -0.28 unidades en el Índice de Sexismo a comparación de las mujeres con educación básica, siendo de forma alta estadísticamente significativa. En cuanto a las mujeres con educación superior, estas poseen en promedio -0.45 unidades a comparación de las mujeres con educación básica, también siendo este efecto de forma alta estadísticamente significativo; los dos efectos mencionados anteriormente se pueden extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Respecto al intercepto, este sugiere que el promedio en el Índice de Sexismo para las mujeres con educación básica es de 2.29, mientras que para las mujeres con educación media es de 2.01 y para las mujeres con educación superior de 1.84. Finalmente, el R2 equivalente a 0.04, al igual que el modelo 1, indica que el modelo 2 logra explicar en un 4% la varianza de la variable dependiente.</p>
<p>En el modelo 3 se utilizó el Índice de Dependencia económica como predictor, el cual se subdivide en 2 categorías: No dependencia económica y Si dependencia económica; en donde se toma como categoría de referencia “No dependencia económica”. Se observa que las mujeres con dependencia económica poseen un coeficiente de regresión de 0.02 unidades más en el Índice de Sexismo que las mujeres sin dependencia económica. Sin embargo, estos coeficientes de regresión no son estadísticamente significativos. Se tiene además que el R2 equivalente a 0.00, indica que este modelo explica en 0% la varianza de la variable dependiente.&nbsp;</p>
<p>En el modelo 4 se utilizó ´Violencia Física a lo largo de la vida´ como predictor, el cual posee un coeficiente de regresión de -0.10, siendo estadísticamente significativo. Esto sugiere que las mujeres que han sufrido violencia física a lo largo de la vida tendrían en promedio -0.10 unidades en el Índice de Sexismo; en donde este efecto se puede extrapolar con un 95% de confianza a la población [**: p&lt;0.01].&nbsp; Por otro lado, el R2 equivalente a 0.00, indica que este modelo explica en un 0% la varianza de la variable dependiente.</p>
<p>En el modelo 5 se utilizó ´Violencia Psicológica a lo largo de la vida´ como predictor, el cual posee un coeficiente de regresión de 0.00. De este modo, según la regresión lineal simple, se observa que este predictor aporta 0% en explicar la varianza de la variable independiente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Regresion Lineal Simple [Parte 2: Modelos del 6 al 10] </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co">#reg7 &lt;- lm(PJFINALroles ~ GSE_REC, data=variables_reg_lin)</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co">#reg8 &lt;- lm(PJFINALroles ~ P26_REC, data=variables_reg_lin)</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co">#reg9 &lt;- lm(PJFINALroles ~ P12_H, data=variables_reg_lin)</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co">#reg10 &lt;- lm(PJFINALroles ~ IND_REDES, data=variables_reg_lin)</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co">#reg11 &lt;- lm(PJFINALroles ~ VE_AÑO, data=variables_reg_lin)</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co">#knitreg(list(reg7, reg8, reg9, reg10, reg11), </span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>        <span class="co">#custom.model.names = c("Modelo 6",</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Modelo 7",</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Modelo 8",</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Modelo 9",</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Modelo 10"),</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="co">#        custom.note = "*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05",</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="co">#        custom.coef.names = c("Intercepto",</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Grupo Socioeconomico",</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Tiempo con la pareja actual",</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Cantidad de Hijos",</span></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Indice de Redes de Apoyo",</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Violencia Economica"),</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="co">#        caption = "Indice de Sexismo",</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a><span class="co">#        caption.above = TRUE) </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/Captura%20de%20pantalla%202025-06-13%20231736.png" class="img-fluid"></p>
<p>En el modelo 6 se utilizó ´Grupo Socioeconómico´ como predictor, el cual posee un coeficiente de regresión de -0.15, siendo de forma alta estadísticamente significativo. Esto indica que, en promedio, por cada unidad que aumente en el grupo socioeconómico el Índice de Sexismo (2.29) en las mujeres se disminuye en 0.15 unidades; este efecto se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Dado que el R2 es equivalente a 0.01, se estima que este modelo logra explicar en un 1% la varianza de la variable dependiente.&nbsp;</p>
<p>En el modelo 7 se utilizó ´Tiempo con la pareja actual´ como predictor, el cual posee un coeficiente de regresión de 0.10, siendo de forma alta estadísticamente significativo. Aquello indica que, en promedio, por cada unidad que aumente el tiempo con la pareja actual el Índice de Sexismo (1.64) se ve aumentado en 0.10 puntos; este efecto se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. En cuanto al R2 equivalente a 0.03, se estima&nbsp; que este modelo logra explicar en un 3% la varianza de la variable dependiente.</p>
<p>En el modelo 8 se utilizó ´Cantidad de Hijos´ como predictor, el cual posee un coeficiente de regresión de 0.05, siendo de forma alta estadísticamente significativo. Aquello indica que, en promedio, por cada unidad aumentada en la cantidad de hijos, el Índice de Sexismo (1.93) se ve aumentado en 0.05 unidades en las mujeres; dicho efecto se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Considerando el R2 equivalente a 0.01, se estima que el este modelo logra explicar en un 1% la varianza de la variable dependiente.</p>
<p>En el modelo 9 se utilizó ´Índice de Redes de apoyo´, el cual posee un coeficiente de regresión de&nbsp; 0.08, siendo de forma alta estadísticamente significativo. Esto indica que, en promedio, por cada unidad aumentada en el Índice de Redes de apoyo, a su vez, el Índice de Sexismo (1.98) se ve aumentando en 0.08 unidades en las mujeres; dicho efecto se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Dado que el R2 es equivalente a 0.01, se estima que este modelo logra explicar en un 1% la varianza de la variable dependiente.</p>
<p>Finalmente, en el modelo 10 se utilizó ´Violencia Económica´ como predictor, el cual posee un coeficiente de regresión de -0.25, siendo de forma alta estadísticamente significativo. Aquello indica que, en promedio, por cada unidad aumentada en la prevalencia de haber vivido violencia económica, el Índice de Sexismo (2.53) se ve disminuido en 0.25 unidades en las mujeres; dicho efecto se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Considerando que el R2 es equivalente a 0.01, se estima que este modelo logra explicar en un 1% la varianza de la variable dependiente.</p>
<p><strong>B) Regresiones lineales múltiples.</strong></p>
<p>Luego de haber realizado los 10 modelos de regresiones lineales simples, se opta por realizar 4 modelos de regresión lineal múltiple –en donde se toman los 10 predictores anteriormente observados—.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">###Regresiones Lineales Multiples</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co">#reg5_m &lt;- lm(PJFINALroles ~ EDAD_O + P4 + GSE_REC, data=variables_reg_lin)</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co">#reg6_m &lt;- lm(PJFINALroles ~ EDAD_O  + P12_H + IND_REDES, data=variables_reg_lin)</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co">#reg7_m &lt;- lm(PJFINALroles ~ P4 + P26_REC + RVGENV_AoV + VPGENV_AoV + VE_AÑO, data=variables_reg_lin)</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co">#reg8_m &lt;- lm(PJFINALroles ~ EDAD_O + P4 + GSE_REC + P12_H + IND_REDES + P26_REC + RVGENV_AoV + VPGENV_AoV + VE_AÑO + IND_DEPECON, data=variables_reg_lin)</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co">#knitreg(list(reg5_m, reg6_m, reg7_m, reg8_m), </span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">#        custom.model.names = c("Modelo 1",</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Modelo 2",</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Modelo 3",</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Modelo 4"),</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="co">#        custom.note = "*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05",</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="co">#        custom.coef.names = c("Intercepto", </span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Edad",</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Sin estudios &lt;br&gt; &lt;i&gt;(Ref. Ed. básica)&lt;/i&gt;",</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Educación media",</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Educación superior", </span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Grupo Socioeconomico",</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Indice de Redes de Apoyo",</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Cantidad de Hijos",</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Tiempo con la pareja actual",</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Violencia Fisica",</span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Violencia Psicologica",</span></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Violencia Economica",</span></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a><span class="co">#                              "Si dependencia economica &lt;br&gt; &lt;i&gt;(Ref. No dependencia economica)&lt;/i&gt;"),</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a><span class="co">#        caption = "Indice de Sexismo",</span></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a><span class="co">#        caption.above = TRUE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/Captura%20de%20pantalla%202025-06-13%20232615.png" class="img-fluid"></p>
<p>En el modelo 1 se utilizan como predictores las variables de: edad, nivel educativo y el grupo socioeconómico. En primer lugar, se puede observar que por cada unidad que aumenta la edad, el Índice de Sexismo aumenta en 0.01 unidades en las mujeres, manteniendo el nivel educativo y el grupo socioeconómico constantes; siendo este efecto estadísticamente significativo [***: p&lt;0.001]. En cuanto al nivel educativo, se observa que, en promedio, no tener estudios disminuye en 0.34 unidades el Índice de Sexismo en comparación a tener educación básica (0.15+ en el Índice de Sexismo); siendo este efecto estadísticamente significativo [*: p&lt;0.05]. Respecto a tener educación media (b= -0.20) y educación superior (b= -0.28), ambas poseen un efecto negativo sobre el Índice de Sexismo en comparación con quienes tienen educación básica, manteniendo la edad y el grupo socioeconómico constantes; ambos efectos son estadísticamente significativos, pudiendo extrapolarse a la población con un 99.9% de confianza [***: p&lt;0.001]. Por otro lado, se observa que, en promedio, por cada unidad aumentada en el grupo socioeconómico, el Índice de Sexismo se ve disminuido en 0.11 unidades en las mujeres, manteniendo la edad y el nivel educativo constantes; dicho efecto es estadísticamente significativo y se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Finalmente, el R2 equivalente a 0.07 nos indica que el modelo 1 logra explicar en un 7% la varianza de la variable dependiente.</p>
<p>En el modelo 2 se utilizan como predictores las variables de: edad, índice de redes de apoyo y cantidad de hijos. En primer lugar, se puede observar que la edad tiene los mismos efectos en el Índice de Sexismo que en el modelo 1, manteniendo el índice de redes de apoyo y cantidad de hijos constantes, siendo estadísticamente significativo [***: p&lt;0.001]. En cuanto al índice de redes de apoyo, este posee un coeficiente de regresión de 0.00, por lo que aporta en un 0% a explicar la variable dependiente, mientras el resto de predictores se mantiene constante. Por otro lado, se observa que, en promedio, por cada unidad que aumenta la cantidad de hijos, el Índice de Sexismo aumenta en 0.08 unidades, manteniendo la edad y el índice de redes de apoyo constante; siendo este efecto estadísticamente significativo y pudiéndose extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Finalmente, el R2 equivalente a 0.04 indica que el modelo 2 permite explicar en un 4% la varianza de la variable dependiente.</p>
<p>En el modelo 3 se utilizan como predictores las variables de: nivel educativo, tiempo con la pareja actual, violencia física, violencia psicológica y violencia económica. En primer lugar, se observa que tener educación media (b= -0.24) y superior (b= -0.38) tienen efectos negativos en el Índice de Sexismo en comparación a las mujeres que tienen educación básica, manteniendo los demás predictores constantes; siendo ambos efectos estadísticamente significativos y pudiéndose extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. También se observa que, en promedio, por cada unidad que aumenta el tiempo en pareja, a su vez aumenta el Índice de Sexismo en 0.08 unidades en la mujeres, manteniendo el resto de predictores constantes; dicho efecto es estadísticamente significativo y se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Por otro lado, se observa que, en promedio, haber sufrido violencia física a lo largo de la vida disminuye en 0.10 unidades el Índice de Sexismo en las mujeres, manteniendo el resto de predictores constantes; dicho efecto es estadísticamente significativo y se puede extrapolar a la población con un 95% de confianza [*: p&lt;0.05]. Respecto a haber sufrido violencia económica, es correcto afirmar que, en promedio, sufrir violencia económica disminuye el Índice de Sexismo en 0.21 unidades en las mujeres, manteniendo el resto de predictores constantes; dicho efecto es estadísticamente significativo y se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Finalmente, el R2 equivalente a 0.07 indica que el modelo 3 logra explicar en un 7% la varianza de la variable dependiente.&nbsp;</p>
<p>Por último, el modelo 4 utiliza los 10 predictores anteriormente mencionados. En primer lugar, se da cuenta que tanto la edad como la violencia física se comportan igual que en los modelos anteriores. Ahora bien, se observa que en el nivel educativo, las mujeres que no tienen estudio –a comparación de las que tienen educación básica— disminuyen el Índice de Sexismo en 0.33, siendo estadísticamente significativo [*: p&lt;0.05]. Las mujeres que tienen educación media (b= -0.19) y superior (b= -27) a comparación de las que tienen educación básica, tienen efectos negativos en el Índice de Sexismo, manteniendo el resto de predictores constantes; siendo ambos efectos estadísticamente significativos y pudiéndose extrapolar a la población con un 99.9% de confianza. Se observa que, en promedio, por cada unidad aumentada en el grupo socioeconómico, el Índice de Sexismo disminuye en 0.10 unidades en las mujeres, manteniendo el resto de los predictores constantes; dicho efecto es estadísticamente significativo y se puede extrapolar a la población con un 99.9% de confianza [***: p&lt;0.001]. Por otro lado, se observa que, en promedio, por cada unidad aumentada en cantidad de hijos, a su vez aumenta el Índice de Sexismo en 0.05 unidades en las mujeres, manteniendo el resto de predictores constantes y siendo estadísticamente significativo [**: p&lt;0.01]. Respecto al tiempo con la pareja actual, por cada unidad aumentada, el Índice de Sexismo se ve aumentando en 0.04 unidades en las mujeres, manteniendo el resto de predictores constante y siendo estadísticamente significativo [*: p&lt;0.05]. Ahora bien, es correcto afirmar que, en promedio, haber sufrido violencia económica disminuye en 0.20 unidades el Índice de Sexismo en las mujeres, manteniendo el resto de predictores constante; dicho efecto es estadísticamente significativo y se puede extrapolar con un 99.9% de confianza [***: p&lt;0.001]. Por último, considerando que el R2 equivale a 0.08, se estima que el modelo 4 logra explicar en un 8% la varianza de la variable dependiente.</p>
<p><strong>Gráfico del modelo 4 de la regresión lineal múltiple.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Graficar el modelo 4 de regresion lineal multiple [con los 10 predictores]</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot_model(reg8_m, </span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#           title = "", #quitar titulo</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co">#           show.values = TRUE, #mostrar valor de efectos</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co">#           dot.size = 3, #tamaño circulos</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co">#           line.size = 1, #tamaño CI</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co">#           value.size = 4, #tamaño valor efectoss</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co">#           spacing = 1, #espacio entre efectos</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co">#           vline.color = "red", # linea roja en punto neutro (0)</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co">#           axis.labels = rev(c("Edad",</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Sin estudios",</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Educación media", </span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Educación superior",</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Grupo Socioeconomico",</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Indice de Redes de Apoyo",</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Cantidad de Hijos",</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Tiempo con la pareja actual",</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Violencia Fisica",</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Violencia Psicologica",</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Violencia Economica",</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="co">#                               "Si dependencia economica")),</span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="co">#           show.legend = FALSE) + # variables dependientes</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="co">#  theme_bw()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/Captura%20de%20pantalla%202025-06-13%20233035.png" class="img-fluid"></p>
<p><strong>Figura 8:</strong> Modelo 4 de regresión lineal múltiple.</p>
<p>En la figura 8 se ilustra mejor cómo se comportan los predictores del modelo 4. Se puede observar como los predictores ´Edad´, ´Cantidad de hijos´ y ´Tiempo con la pareja actual´ se ubican en el hemisferio positivo de los valores estimados, teniendo así efectos positivos en el Índice de Sexismo [variable dependiente] y siendo estadísticamente significativos. Por otro lado, tenemos que los predictores ´Nivel educativo´ (tomando como referencia educación básica y conformado por las categorías : Sin estudios, educación media y superior), ´Grupo socioeconómico´, ´Violencia Física´ y ´Violencia Económica´, se encuentran en el hemisferio negativo de los valores estimados, teniendo así efectos negativos en el Índice de Sexismo [variable dependiente]. Mientras que los predictores ´Índice de redes de apoyo´ e ´Índice de Dependencia económica´ si bien tienen efectos negativos en la variable dependiente, estos no son estadísticamente significativos. Mismo caso con el predictor de ´Violencia psicológica´ que si bien tiene efectos positivos en la variable dependiente, estos no son estadísticamente significativos.&nbsp;</p>
<p><strong>Gráfico de valores predichos del predictor ´Edad´ [EDAD_O]</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">###Grafico de valores predichos del predictor: Edad</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co">#ggeffects::ggpredict(reg8_m, terms="EDAD_O") %&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ggplot(mapping=aes(x = x, y=predicted)) +</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  labs(title="Edad", x = "", y = "")+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co">#  theme_bw() +</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co">#  geom_smooth()+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co">#  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .2, fill = "black") +</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co">#  scale_x_continuous(breaks = seq(0,100, by = 10))+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co">#  scale_y_continuous(limits = c(0,16), </span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="co">#                     breaks = seq(0,16, by = 1))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/Captura%20de%20pantalla%202025-06-13%20233318.png" class="img-fluid"></p>
<p>Se puede observar que los valores predichos de la variable ´Edad´ como predictor del Índice de Sexismo [Variable dependiente], toman una dirección de orientación ligeramente positiva –es decir, débil-–. De este modo, es posible decir que las mujeres de esta muestra, mientras más edad posean se va a tender a un mayor Índice de Sexismo, lo cual se puede afirmar con confianza estadística, dado el área gris –intervalo de confianza— que rodea la línea azul.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-bituga-nchama2021" class="csl-entry" role="listitem">
Bituga-Nchama, Pedro. 2021. <span>“Estereotipos de Género En La Construcción de La Mujer Fang: Una Educación Patriarcal Para La Sumisión.”</span> <em>Cátedra</em> 3 (3): 143–60. <a href="https://doi.org/10.29166/catedra.v3i3.2465">https://doi.org/10.29166/catedra.v3i3.2465</a>.
</div>
<div id="ref-maguiña" class="csl-entry" role="listitem">
Maguiña, Franklin Roberth Rosales. n.d. <span>“SEXISMO EN ADOLESCENTES ESTUDIANTES DE UNA INSTITUCIÓN EDUCATIVA PARROQUIAL DE HUARAZ, 2016.”</span>
</div>
<div id="ref-oviedo2005" class="csl-entry" role="listitem">
Oviedo, Heidi Celina, and Adalberto Campo-Arias. 2005. <span>“de investigación y lectura crítica de estudios.”</span> <em>Revista Colombiana de Psiquiatría</em>, no. 4.
</div>
<div id="ref-rodríguezenríquez2012" class="csl-entry" role="listitem">
Rodríguez Enríquez, Corina. 2012. <span>“La cuestión del cuidado: ¿El eslabón perdido del análisis económico?”</span> <em>Revista de la CEPAL</em> 2012 (106): 23–36. <a href="https://doi.org/10.18356/9241f4b8-es">https://doi.org/10.18356/9241f4b8-es</a>.
</div>
<div id="ref-toca2008" class="csl-entry" role="listitem">
Toca, Isabel García, and Fernanda Nader Carreta. 2008. <span>“Estereotipos Masculinos en la Relación de Pareja.”</span> <em>Revista Internacional de Psicología</em> 9 (01): 1–11. <a href="https://doi.org/10.33670/18181023.v9i01.49">https://doi.org/10.33670/18181023.v9i01.49</a>.
</div>
<div id="ref-virgilio" class="csl-entry" role="listitem">
Virgilio, María Eugenia De. n.d. <span>“Dependencia económica de la mujer ¿Un campo fértil para la perpetuación en un ambiente de violencia? Relatos de mujeres asistidas en el Juzgado de Faltas de Barranqueras.”</span>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>